# Generated by Django 2.0.7 on 2018-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_raza_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
